defaults:
  - GradDiff

handler: SimNPO
method_args:
  delta: 0.0 # gamma in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
  beta: 0.75
  alpha: 1.0
  gamma: 1.0 # npo_coeff in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
  retain_loss_type: NLL

# method_args:
#   delta: 0.0 # gamma in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
#   beta: 4.5
#   alpha: 1.0
#   gamma: 0.125 # npo_coeff in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
#   retain_loss_type: NLL



# Parameters here: https://huggingface.co/collections/OPTML-Group/simnpo-unlearned-models

# MUSE BOOKS
# method_args:
#   delta: 0.0 # gamma in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
#   beta: 0.75
#   alpha: 1.0
#   gamma: 1.0 # npo_coeff in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
#   retain_loss_type: NLL

# MUSE NEWS
# method_args:
#   delta: 3.0 # gamma in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
#   beta: 0.7
#   alpha: 1.0
#   gamma: 1.0 # npo_coeff in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
#   retain_loss_type: NLL

# TOFU FORGET 05 - llama 2 7b chat
# method_args:
#   delta: 0.0 # gamma in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
#   beta: 2.5
#   alpha: 0.135
#   gamma: 1 # npo_coeff in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
#   retain_loss_type: NLL

# TOFU FORGET 10 - llama 2 7b chat
# method_args:
#   delta: 0.0 # gamma in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
#   beta: 4.5
#   alpha: 1.0
#   gamma: 0.125 # npo_coeff in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
#   retain_loss_type: NLL
