# @package eval.tofu.metrics.retain_extraction_strength
defaults:
  - ../../data/datasets@datasets: TOFU_QA_retain_eval
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: extraction_strength
batch_size: ${eval.tofu.batch_size}

datasets:
  TOFU_QA_retain_eval:
    args:
      question_key: ${eval.tofu.question_key}
